---
version: 2
jobs:
    build:
        docker:
            # specify the version you desire here
            - image: cimg/openjdk:11.0.13
        environment:
            # Customize the JVM maximum heap limit
            JVM_OPTS: -Xmx500m
            TERM: dumb
        steps:
            - checkout
            - run: ./gradlew dependencies
            - run: ./gradlew test
            - run: ./gradlew jar
            - store_artifacts:
                  path: build/libs
